build:
	go build -o ${GOPATH}/bin/dockerserver dockerservermain.go;
	go build -o ${GOPATH}/bin/dockerclient dockerclientmain.go;
	go build -o ${GOPATH}/bin/bitverseserver bitverseservertest.go;
	go build -o ${GOPATH}/bin/bitverseclient bitverseclienttest.go;
	go build -o ${GOPATH}/bin/protocoltest protocoltest.go;

